import { CalendarClock, CheckCircle2 } from "lucide-react";
import { Link } from "react-router-dom";
import PriorityBadge from "../tasks/PriorityBadge";
import TaskStatusBadge from "../tasks/TaskStatusBadge";

const progressFor = (task) => Number(task.progress ?? ({ TO_DO: 10, IN_PROGRESS: 55, SUBMITTED_FOR_REVIEW: 85, CHANGES_REQUIRED: 65, COMPLETED: 100 }[task.status] || 0));
const rank = (task) => task.status === "IN_PROGRESS" && task.activeSessionStartedAt ? 0 : task.status === "IN_PROGRESS" ? 1 : task.status === "CHANGES_REQUIRED" ? 2 : task.status === "TO_DO" ? 3 : 4;
const deadline = (value, overdue) => {
  if (!value) return "No deadline";
  const target = new Date(value), now = new Date(), tomorrow = new Date(now); tomorrow.setDate(now.getDate() + 1);
  const same = (a,b) => a.toDateString() === b.toDateString();
  const day = same(target, now) ? "Due today" : same(target, tomorrow) ? "Due tomorrow" : `Due ${new Intl.DateTimeFormat("en-PK", { day: "numeric", month: "short" }).format(target)}`;
  const at = new Intl.DateTimeFormat("en-PK", { hour: "numeric", minute: "2-digit" }).format(target);
  return overdue ? `Overdue · ${day.replace("Due ", "")}` : `${day} · ${at}`;
};

export default function EmployeeMyTasks({ tasks = [], loading, busy, onOpen, onStart }) {
  const visible = tasks.filter((task) => !["OPEN", "DRAFT", "SCHEDULED", "ARCHIVED", "COMPLETED"].includes(task.status)).sort((a,b) => rank(a)-rank(b) || new Date(a.due_at || "9999-12-31")-new Date(b.due_at || "9999-12-31"));
  const primary = visible[0], next = visible.slice(1,4);
  const action = primary?.status === "TO_DO" ? "Start task" : ["CHANGES_REQUIRED"].includes(primary?.status) || (primary?.status === "IN_PROGRESS" && !primary?.activeSessionStartedAt) ? "Resume task" : "View task";
  return <section className="flex min-h-[360px] min-w-0 flex-col rounded-3xl border border-border bg-surface p-5 shadow-sm"><div className="flex items-start justify-between"><div><h2 className="font-bold">My Tasks</h2><p className="text-xs text-muted-foreground">Your current priorities</p></div><Link to="/tasks" className="text-xs font-semibold text-primary-text">View all →</Link></div>{loading ? <div className="mt-5 space-y-3"><div className="h-32 animate-pulse rounded-2xl bg-surface-secondary"/><div className="h-10 animate-pulse rounded-xl bg-surface-secondary"/></div> : !primary ? <div className="grid flex-1 place-items-center py-8 text-center"><div><CheckCircle2 className="mx-auto text-success"/><p className="mt-3 font-semibold">You&apos;re all caught up</p><p className="mt-1 text-xs text-muted-foreground">No active tasks assigned.</p><Link to="/tasks" className="mt-4 inline-block text-xs font-semibold text-primary-text">View tasks</Link></div></div> : <><button onClick={() => onOpen(primary)} className="mt-5 w-full rounded-2xl bg-surface-secondary/70 p-4 text-left"><p className="text-[10px] font-bold uppercase tracking-wider text-primary-text">Current task</p><h3 className="mt-2 line-clamp-2 font-bold">{primary.title}</h3><p className="mt-1 text-xs text-muted-foreground">{primary.assignment_type === "OPEN" ? "Open assignment" : "Direct assignment"}</p><div className="mt-3 flex flex-wrap gap-2"><PriorityBadge priority={primary.priority}/><TaskStatusBadge status={primary.status}/></div><div className="mt-4 flex justify-between text-[11px]"><span className="text-muted-foreground">Progress</span><strong>{progressFor(primary)}%</strong></div><div className="mt-1 h-1.5 overflow-hidden rounded-full bg-border"><div className="h-full rounded-full bg-primary" style={{width:`${progressFor(primary)}%`}}/></div><p className={`mt-3 flex items-center gap-1 text-xs ${primary.overdue ? "font-semibold text-danger" : "text-muted-foreground"}`}><CalendarClock size={13}/>{deadline(primary.due_at, primary.overdue)}</p></button><button disabled={busy} onClick={() => action === "View task" ? onOpen(primary) : onStart(primary)} className="mt-3 w-full rounded-xl bg-primary px-3 py-2.5 text-xs font-semibold text-primary-foreground disabled:opacity-60">{busy ? "Updating…" : action}</button>{next.length > 0 && <div className="mt-5"><p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Next tasks</p><div className="mt-2 divide-y divide-border">{next.map(task => <button key={task.id} onClick={() => onOpen(task)} className="flex w-full items-center justify-between gap-3 py-2.5 text-left"><div className="min-w-0"><p className="truncate text-xs font-semibold">{task.title}</p><p className="text-[10px] text-muted-foreground">{task.priority} · {deadline(task.due_at, task.overdue)}</p></div><span className="text-[10px] font-semibold">{progressFor(task)}%</span></button>)}</div></div>}</>}</section>;
}
