import { Link } from "react-router-dom";
import { initials } from "../../utils/helpers";
import AvailabilityBadge from "../availability/AvailabilityBadge";

export default function EmployeeTeamAvailability({ data, connected, activity = [] }) {
  const people = data?.employees || [], counts = data?.counts || {};
  const metrics = [["Online", counts.ONLINE, "bg-success"], ["Away", counts.AWAY, "bg-warning"], ["Break", counts.ON_BREAK, "bg-warning"], ["Meeting", counts.IN_MEETING, "bg-primary"], ["Offline", counts.OFFLINE, "bg-muted-foreground"]];
  return <section className="flex min-h-[360px] min-w-0 flex-col rounded-3xl border border-border bg-surface p-5 shadow-sm"><div className="flex items-start justify-between"><div><h2 className="font-bold">Team Availability</h2><p className="text-xs text-muted-foreground">Live office status</p></div><span className="inline-flex items-center gap-1.5 rounded-full bg-primary-soft px-2.5 py-1 text-[10px] font-bold text-primary-text"><i className="h-1.5 w-1.5 rounded-full bg-primary"/>{connected ? "LIVE" : "CONNECTING"}</span></div><div className="mt-4 flex flex-wrap gap-x-3 gap-y-2 rounded-xl bg-surface-secondary/70 p-3">{metrics.map(([label,value,color]) => <span key={label} className="flex items-center gap-1.5 text-[10px]"><i className={`h-1.5 w-1.5 rounded-full ${color}`}/><strong>{value || 0}</strong><span className="text-muted-foreground">{label}</span></span>)}</div><div className="mt-3 divide-y divide-border">{people.slice(0,5).map(person => <div key={person.employeeId} className="grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-2 py-2.5"><span className="grid h-8 w-8 place-items-center rounded-full bg-primary-soft text-[10px] font-bold text-primary-text">{initials(person.employeeName)}</span><div className="min-w-0"><p className="truncate text-xs font-semibold">{person.employeeName}</p><p className="truncate text-[10px] text-muted-foreground">Attendance: {person.attendance === "CLOCKED_IN" ? "Clocked in" : person.attendance === "ON_BREAK" ? "On break" : "Clocked out"}</p></div><AvailabilityBadge status={person.availability}/></div>)}</div>{people.length > 5 && <p className="mt-2 text-[10px] text-muted-foreground">+ {people.length - 5} more team members</p>}{activity.length > 0 && <div className="mt-auto border-t border-border pt-3"><Link to="/attendance" className="text-[10px] font-semibold text-primary-text">Recent activity</Link><p className="mt-1 truncate text-[10px] text-muted-foreground">{activity[activity.length - 1]?.type?.replaceAll("_", " ")}</p></div>}</section>;
}
