-- Task Management Phase 1: additive backend foundation; preserves all existing data.
CREATE TABLE task_settings(
 id TINYINT UNSIGNED PRIMARY KEY DEFAULT 1,offline_timeout_minutes SMALLINT UNSIGNED NOT NULL DEFAULT 5,
 max_open_claims_per_employee SMALLINT UNSIGNED NOT NULL DEFAULT 3,updated_by BIGINT UNSIGNED NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 CHECK(offline_timeout_minutes BETWEEN 1 AND 1440),CHECK(max_open_claims_per_employee BETWEEN 0 AND 100),
 FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO task_settings(id) VALUES(1);
CREATE TABLE tasks(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(200) NOT NULL,description TEXT NULL,instructions TEXT NULL,
 priority ENUM('LOW','MEDIUM','HIGH','URGENT') NOT NULL DEFAULT 'MEDIUM',assignment_type ENUM('DIRECT','OPEN') NOT NULL,
 assignee_employee_id BIGINT UNSIGNED NULL,status ENUM('DRAFT','SCHEDULED','OPEN','TO_DO','IN_PROGRESS','SUBMITTED_FOR_REVIEW','CHANGES_REQUIRED','COMPLETED','ARCHIVED') NOT NULL,
 start_at DATETIME NULL,due_at DATETIME NULL,publish_mode ENUM('DRAFT','NOW','SCHEDULED') NOT NULL DEFAULT 'DRAFT',scheduled_publish_at DATETIME NULL,published_at DATETIME NULL,
 review_required BOOLEAN NOT NULL DEFAULT FALSE,completion_image_required BOOLEAN NOT NULL DEFAULT FALSE,
 submitted_at DATETIME NULL,completed_at DATETIME NULL,archived_at DATETIME NULL,created_by BIGINT UNSIGNED NOT NULL,updated_by BIGINT UNSIGNED NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(assignee_employee_id) REFERENCES employees(id) ON DELETE RESTRICT,FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE RESTRICT,FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE SET NULL,
 INDEX idx_tasks_status_priority_due(status,priority,due_at),INDEX idx_tasks_assignment_status(assignment_type,status),INDEX idx_tasks_assignee_status(assignee_employee_id,status),INDEX idx_tasks_creator(created_by),INDEX idx_tasks_schedule(status,scheduled_publish_at),FULLTEXT KEY ft_tasks_title_description(title,description)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE task_images(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,task_id BIGINT UNSIGNED NOT NULL,uploaded_by BIGINT UNSIGNED NOT NULL,image_context ENUM('TASK_REFERENCE','SUBMISSION','CHANGES_REQUIRED') NOT NULL,storage_key VARCHAR(500) NOT NULL,original_filename VARCHAR(255) NOT NULL,mime_type ENUM('image/jpeg','image/png','image/webp','image/gif') NOT NULL,size_bytes INT UNSIGNED NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE,FOREIGN KEY(uploaded_by) REFERENCES users(id) ON DELETE RESTRICT,INDEX idx_task_images_context(task_id,image_context));
CREATE TABLE task_comments(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,task_id BIGINT UNSIGNED NOT NULL,author_user_id BIGINT UNSIGNED NOT NULL,content VARCHAR(1000) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE,FOREIGN KEY(author_user_id) REFERENCES users(id) ON DELETE RESTRICT,INDEX idx_task_comments(task_id,created_at));
CREATE TABLE task_activities(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,task_id BIGINT UNSIGNED NOT NULL,event_type VARCHAR(60) NOT NULL,actor_user_id BIGINT UNSIGNED NULL,previous_status VARCHAR(40) NULL,new_status VARCHAR(40) NULL,metadata JSON NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE,FOREIGN KEY(actor_user_id) REFERENCES users(id) ON DELETE SET NULL,INDEX idx_task_activity(task_id,created_at),INDEX idx_task_activity_event(event_type,created_at));
CREATE TABLE task_change_requests(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,task_id BIGINT UNSIGNED NOT NULL,requested_by BIGINT UNSIGNED NOT NULL,reason VARCHAR(1000) NOT NULL,previous_due_at DATETIME NULL,revision_due_at DATETIME NULL,resolved_at DATETIME NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE,FOREIGN KEY(requested_by) REFERENCES users(id) ON DELETE RESTRICT,INDEX idx_task_changes(task_id,created_at));
CREATE TABLE task_assignment_history(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,task_id BIGINT UNSIGNED NOT NULL,previous_employee_id BIGINT UNSIGNED NULL,new_employee_id BIGINT UNSIGNED NULL,changed_by BIGINT UNSIGNED NOT NULL,reason VARCHAR(1000) NULL,assignment_source ENUM('DIRECT','CLAIM','REASSIGN') NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE,FOREIGN KEY(previous_employee_id) REFERENCES employees(id) ON DELETE SET NULL,FOREIGN KEY(new_employee_id) REFERENCES employees(id) ON DELETE SET NULL,FOREIGN KEY(changed_by) REFERENCES users(id) ON DELETE RESTRICT,INDEX idx_task_assignments(task_id,created_at),INDEX idx_task_assignment_employee(new_employee_id,created_at));
CREATE TABLE task_work_sessions(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,task_id BIGINT UNSIGNED NOT NULL,employee_id BIGINT UNSIGNED NOT NULL,started_at DATETIME NOT NULL,ended_at DATETIME NULL,duration_seconds INT UNSIGNED NULL,end_reason ENUM('PAUSED','BREAK','CLOCK_OUT','OFFLINE','SUBMITTED','COMPLETED','REASSIGNED') NULL,state ENUM('ACTIVE','ENDED') NOT NULL DEFAULT 'ACTIVE',active_employee_id BIGINT UNSIGNED GENERATED ALWAYS AS(IF(state='ACTIVE',employee_id,NULL)) STORED,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE,FOREIGN KEY(employee_id) REFERENCES employees(id) ON DELETE RESTRICT,UNIQUE KEY uq_one_active_task_per_employee(active_employee_id),INDEX idx_task_sessions(task_id,employee_id,started_at));
INSERT INTO permissions(name,description) VALUES
('task.view_own','View own and available open tasks'),('task.view_all','View all tasks'),('task.create','Create tasks and drafts'),('task.edit','Edit tasks'),('task.assign','Assign and reassign tasks'),('task.claim','Claim open tasks'),('task.manage','Manage task workflow'),('task.review','Review submitted tasks'),('task.archive','Archive and restore tasks'),('task.delete','Permanently delete archived tasks'),('task.analytics','View task analytics'),('task.settings','Manage task settings');
INSERT IGNORE INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.name IN('task.view_own','task.view_all','task.create','task.edit','task.assign','task.manage','task.review','task.archive','task.delete','task.analytics','task.settings') WHERE UPPER(r.name) IN('CEO','ADMIN','SUPER_ADMIN');
INSERT IGNORE INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.name IN('task.view_own','task.claim') WHERE UPPER(r.name)='EMPLOYEE';
INSERT INTO notification_policies(event_type,audience_type,in_app_enabled,desktop_enabled,sound_enabled) VALUES('OPEN_TASK_CREATED','ALL_EMPLOYEES',1,0,0),('TASK_CLAIMED','CEO_ADMIN',1,0,0),('TASK_STARTED','CEO_ADMIN',1,0,0),('TASK_SUBMITTED','CEO_ADMIN',1,1,0),('TASK_CHANGES_REQUIRED','SELECTED_EMPLOYEES',1,1,0),('TASK_COMPLETED','CEO_ADMIN',1,0,0),('TASK_OVERDUE','SELECTED_EMPLOYEES',1,1,0),('TASK_COMMENT_ADDED','SELECTED_EMPLOYEES',1,0,0),('TASK_DEADLINE_CHANGED','SELECTED_EMPLOYEES',1,1,0),('TASK_REOPENED','SELECTED_EMPLOYEES',1,1,0);
