import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, Clock3, Layers3, MessageSquare, Repeat2 } from "lucide-react";
import Button from "../common/Button";
import Loader from "../common/Loader";
import * as api from "../../services/dayEndReport.service";
import { errorMessage } from "../../utils/helpers";

const iso = (date) => new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Karachi" }).format(date);
const shift = (date, days) => { const value = new Date(date); value.setDate(value.getDate() + days); return value; };
const monthRange = (offset = 0) => { const now = new Date(), start = new Date(now.getFullYear(), now.getMonth() + offset, 1), end = new Date(now.getFullYear(), now.getMonth() + offset + 1, 0); return [iso(start), iso(end)]; };
const weekRange = (offset = 0) => { const now = new Date(), day = (now.getDay() + 6) % 7, start = shift(now, -day + offset * 7); return [iso(start), iso(shift(start, 6))]; };
const rangeFor = (value) => value === "THIS_WEEK" ? weekRange() : value === "LAST_WEEK" ? weekRange(-1) : value === "THIS_MONTH" ? monthRange() : monthRange(-1);
const duration = (minutes) => `${Math.floor(Number(minutes || 0) / 60)}h ${Number(minutes || 0) % 60}m`;
const blockerLabels = { WAITING_ADMIN: "Waiting for CEO/Admin", WAITING_CLIENT: "Waiting for Client", WAITING_TEAM: "Waiting for Team Member", TECHNICAL: "Technical Issue", MISSING_ASSETS: "Missing Information", OTHER: "Other" };
const dateLabel = (value) => new Date(`${value}T00:00:00`).toLocaleDateString("en-PK", { month: "short", day: "numeric" });

function Bars({ rows, keys, onRowClick }) {
  const max = Math.max(1, ...rows.flatMap((row) => keys.map((key) => Number(row[key] || 0))));
  return <div className="mt-5 flex h-52 items-end gap-2 overflow-x-auto pb-1">{rows.map((row) => <button type="button" disabled={!onRowClick} onClick={() => onRowClick?.(row)} key={row.reportDate} className="flex min-w-12 flex-1 flex-col items-center gap-1 disabled:cursor-default"><div className="flex h-40 items-end gap-1">{keys.map((key, index) => <div key={key} title={`${key}: ${row[key] || 0}`} className={`w-3 rounded-t ${index ? "bg-warning" : "bg-primary"}`} style={{ height: `${Math.max(3, Number(row[key] || 0) / max * 100)}%` }}/>)}</div><span className="text-[10px] text-muted-foreground">{dateLabel(row.reportDate)}</span></button>)}</div>;
}

export default function DayEndReportAnalytics({ onOpenReport, onDrillDown }) {
  const [preset, setPreset] = useState("THIS_WEEK"), [from, setFrom] = useState(() => weekRange()[0]), [to, setTo] = useState(() => weekRange()[1]), [employeeId, setEmployeeId] = useState(""), [data, setData] = useState(null), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const load = useCallback(() => { setLoading(true); setError(""); return api.getAnalytics({ from, to, ...(employeeId ? { employeeId } : {}) }).then(setData).catch((e) => setError(errorMessage(e))).finally(() => setLoading(false)); }, [from, to, employeeId]);
  useEffect(() => { load(); }, [load]);
  const choosePreset = (value) => { setPreset(value); if (value !== "CUSTOM") { const [start, end] = rangeFor(value); setFrom(start); setTo(end); } };
  const summary = data?.summary || {}, noData = !loading && !summary.reportsSubmitted;
  const blockerMap = useMemo(() => new Map((data?.blockers || []).map((x) => [x.blockerType, x.count])), [data]);
  if (loading && !data) return <Loader />;
  return <div className="space-y-5">
    <section className="flex flex-wrap gap-3 rounded-2xl border border-border bg-surface p-4">
      <select value={preset} onChange={(e) => choosePreset(e.target.value)} className="rounded-xl border border-border bg-surface px-3 py-2"><option value="THIS_WEEK">This Week</option><option value="LAST_WEEK">Last Week</option><option value="THIS_MONTH">This Month</option><option value="LAST_MONTH">Last Month</option><option value="CUSTOM">Custom Range</option></select>
      {preset === "CUSTOM" && <><input type="date" value={from} onChange={(e) => setFrom(e.target.value)} className="rounded-xl border border-border bg-surface px-3"/><input type="date" value={to} min={from} onChange={(e) => setTo(e.target.value)} className="rounded-xl border border-border bg-surface px-3"/></>}
      <select value={employeeId} onChange={(e) => setEmployeeId(e.target.value)} className="min-w-48 rounded-xl border border-border bg-surface px-3"><option value="">All Employees</option>{data?.employees?.map((employee) => <option key={employee.id} value={employee.id}>{employee.name}</option>)}</select>
      <span className="self-center text-sm text-muted-foreground">{dateLabel(from)} – {dateLabel(to)}</span>
    </section>
    {error && <p className="rounded-xl bg-danger-soft p-3 text-danger">{error}</p>}
    {noData && <p className="rounded-2xl border border-border bg-surface p-8 text-center text-muted-foreground">No Day-End Report data is available for this period.</p>}
    <section className="grid grid-cols-2 gap-3 lg:grid-cols-3 xl:grid-cols-6">{[
      [MessageSquare,"Reports",summary.reportsSubmitted || 0,() => onDrillDown({ date: to })],
      [Layers3,"Work Items",summary.workItems || 0,null],
      [CheckCircle2,"Completed",summary.completed || 0,null],
      [Repeat2,"Carry Forward",summary.carryForwardOccurrences || 0,null],
      [AlertTriangle,"Blockers",summary.blockerReports || 0,() => onDrillDown({ blocker: "HAS_BLOCKER", date: to })],
      [Clock3,"Tracked Task Time",duration(summary.trackedMinutes),null],
    ].map(([Icon,label,value,action]) => <button type="button" disabled={!action} onClick={action || undefined} key={label} className="rounded-2xl border border-border bg-surface p-4 text-left shadow-sm disabled:cursor-default"><Icon size={17} className="text-primary-text"/><b className="mt-3 block text-xl">{value}</b><span className="text-xs text-muted-foreground">{label}</span></button>)}</section>
    <div className="grid gap-5 xl:grid-cols-2"><section className="rounded-2xl border border-border bg-surface p-5"><h2 className="font-black">Work Activity</h2><p className="text-xs text-muted-foreground">Completed and pending snapshot occurrences</p>{data?.trend?.length ? <Bars rows={data.trend} keys={["completed","pending"]} onRowClick={employeeId ? (row) => onOpenReport(row.reportId) : null}/> : <p className="mt-6 text-sm text-muted-foreground">No work activity in this period.</p>}</section><section className="rounded-2xl border border-border bg-surface p-5"><h2 className="font-black">Tracked Task Time</h2><p className="text-xs text-muted-foreground">Task Management snapshots only</p>{data?.trend?.length ? <Bars rows={data.trend} keys={["trackedMinutes"]} onRowClick={employeeId ? (row) => onOpenReport(row.reportId) : null}/> : <p className="mt-6 text-sm text-muted-foreground">No tracked time in this period.</p>}</section></div>
    <div className="grid gap-5 lg:grid-cols-3"><section className="rounded-2xl border border-border bg-surface p-5"><h2 className="font-black">Work Source</h2><Metric label="Task Management" value={data?.sources?.task || 0}/><Metric label="Ongoing Work" value={data?.sources?.ongoingWork || 0}/></section><section className="rounded-2xl border border-border bg-surface p-5"><h2 className="font-black">Report Completion</h2><Metric label="Expected Workdays" value={data?.attendance?.expectedWorkdays || 0}/><Metric label="Reports Submitted" value={data?.attendance?.reportsSubmitted || 0}/><Metric label="Outstanding / Missing" value={data?.attendance?.outstanding || 0}/></section><section className="rounded-2xl border border-border bg-surface p-5"><h2 className="font-black">Review Status</h2><Metric label="Reviewed" value={data?.review?.reviewed || 0}/><button onClick={() => onDrillDown({ status: "SUBMITTED" })} className="w-full"><Metric label="Awaiting Review" value={data?.review?.awaitingReview || 0}/></button><Metric label="Reports With Discussion" value={summary.reportsWithDiscussion || 0}/></section></div>
    <div className="grid gap-5 xl:grid-cols-2"><section className="rounded-2xl border border-border bg-surface p-5"><h2 className="font-black">Blockers</h2>{Object.keys(blockerLabels).map((key) => <button key={key} onClick={() => onDrillDown({ blocker: key, date: to })} className="block w-full"><Metric label={blockerLabels[key]} value={blockerMap.get(key) || 0}/></button>)}</section><section className="rounded-2xl border border-border bg-surface p-5"><h2 className="font-black">Blockers by Day</h2>{data?.blockerTrend?.length ? <Bars rows={data.blockerTrend} keys={["count"]}/> : <p className="mt-5 text-sm text-muted-foreground">No blockers were reported during this period.</p>}</section></div>
    <section className="rounded-2xl border border-border bg-surface p-5"><h2 className="font-black">Needs Attention</h2><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><Attention label="Overdue Reports" value={data?.attention?.overdue} onClick={() => onDrillDown({ attention: true, date: to })}/><Attention label="Waiting for CEO/Admin" value={data?.attention?.waitingAdmin} onClick={() => onDrillDown({ blocker: "WAITING_ADMIN", date: to })}/><Attention label="Technical Blockers" value={data?.attention?.technicalBlockers} onClick={() => onDrillDown({ blocker: "TECHNICAL", date: to })}/><Attention label="Awaiting Review" value={data?.attention?.awaitingReview} onClick={() => onDrillDown({ status: "SUBMITTED", date: to })}/></div></section>
    <section className="rounded-2xl border border-border bg-surface p-5"><h2 className="font-black">Work Carrying Forward</h2><div className="mt-3 grid gap-3 lg:grid-cols-2">{data?.carryForward?.map((item) => <article key={`${item.employeeId}-${item.sourceType}-${item.title}`} className="rounded-xl border border-border p-4"><span className="text-[10px] font-bold text-primary-text">{item.sourceType === "TASK" ? "TASK" : "ONGOING WORK"}</span><h3 className="mt-1 font-bold">{item.title}</h3><p className="text-xs text-muted-foreground">{item.employeeName} · Last reported {item.reportDate}</p>{item.whatsLeft && <p className="mt-2 text-sm">{item.whatsLeft}</p>}<p className="mt-2 text-xs">Estimated remaining: {duration(item.estimatedRemainingMinutes)}</p>{item.blockerType !== "NONE" && <p className="text-xs font-bold text-warning">{blockerLabels[item.blockerType]}</p>}<Button variant="secondary" className="mt-3" onClick={() => onOpenReport(item.reportId)}>View Report</Button></article>)}{!data?.carryForward?.length && <p className="text-sm text-muted-foreground">No work is currently carrying forward from this period.</p>}</div></section>
    <section className="rounded-2xl border border-border bg-surface p-5"><h2 className="font-black">Team Next Priorities</h2><div className="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data?.priorities?.map((item) => <button key={item.employeeId} onClick={() => onOpenReport(item.reportId)} className="rounded-xl bg-surface-secondary p-4 text-left"><b>{item.employeeName}</b><p className="mt-1 whitespace-pre-wrap text-sm text-muted-foreground">{item.tomorrowPriority}</p><span className="mt-2 block text-[10px]">From {item.reportDate}</span></button>)}</div></section>
  </div>;
}
function Metric({ label, value }) { return <div className="mt-3 flex items-center justify-between border-b border-border pb-2 text-sm"><span className="text-muted-foreground">{label}</span><b>{value}</b></div>; }
function Attention({ label, value = 0, onClick }) { return <button onClick={onClick} className="rounded-xl bg-surface-secondary p-4 text-left"><b className="text-xl">{value || 0}</b><span className="mt-1 block text-xs text-muted-foreground">{label}</span></button>; }
