import { Router } from "express";
import { authenticate } from "../middleware/auth.middleware.js";
import auth from "./auth.routes.js";
import employees from "./employee.routes.js";
import roles from "./role.routes.js";
import permissions from "./permission.routes.js";
import audit from "./audit.routes.js";
import dashboard from "./dashboard.routes.js";
import attendance from "./attendance.routes.js";
import leaves from "./leave.routes.js";
import calendar from "./companyCalendar.routes.js";
const r = Router();
r.use("/auth", auth);
r.use(authenticate);
r.use("/dashboard", dashboard);
r.use("/attendance", attendance);
r.use("/leaves", leaves);
r.use("/company-calendar", calendar);
r.use("/employees", employees);
r.use("/roles", roles);
r.use("/permissions", permissions);
r.use("/audit-logs", audit);
export default r;
