export const PERMISSIONS = {
  DASHBOARD: "dashboard.view",
  EMPLOYEES_OWN: "employees.view_own",
  EMPLOYEES_ALL: "employees.view_all",
  EMPLOYEES_CREATE: "employees.create",
  EMPLOYEES_UPDATE: "employees.update",
  EMPLOYEES_DEACTIVATE: "employees.deactivate",
  ROLES_VIEW: "roles.view",
  ROLES_MANAGE: "roles.manage",
  PERMISSIONS_VIEW: "permissions.view",
  PERMISSIONS_MANAGE: "permissions.manage",
  AUDIT_VIEW: "audit.view",
  ATTENDANCE_CLOCK: "attendance.clock",
  ATTENDANCE_OWN: "attendance.view_own",
  ATTENDANCE_ALL: "attendance.view_all",
  ATTENDANCE_EDIT: "attendance.edit",
  ATTENDANCE_REPORTS: "attendance.reports",
  LEAVE_CREATE: "leave.create",
  LEAVE_OWN: "leave.view_own",
  LEAVE_ALL: "leave.view_all",
  LEAVE_APPROVE: "leave.approve",
  LEAVE_REJECT: "leave.reject",
  LEAVE_CANCEL: "leave.cancel_own",
  LEAVE_REPORTS: "leave.reports",
  CALENDAR_VIEW: "calendar.view",
  CALENDAR_MANAGE: "calendar.manage",
};
