-- Additive notification preference upgrade. Existing notification records and
-- category preferences remain authoritative defaults.
ALTER TABLE notification_preferences
  ADD COLUMN notifications_enabled BOOLEAN NOT NULL DEFAULT TRUE AFTER user_id,
  ADD COLUMN in_app_enabled BOOLEAN NOT NULL DEFAULT TRUE AFTER notifications_enabled,
  ADD COLUMN do_not_disturb BOOLEAN NOT NULL DEFAULT FALSE AFTER browser_notifications,
  ADD COLUMN volume TINYINT UNSIGNED NOT NULL DEFAULT 70 AFTER sound_enabled,
  ADD COLUMN calendar_notifications BOOLEAN NOT NULL DEFAULT TRUE AFTER announcement_notifications,
  ADD COLUMN payroll_notifications BOOLEAN NOT NULL DEFAULT TRUE AFTER calendar_notifications,
  ADD COLUMN security_notifications BOOLEAN NOT NULL DEFAULT TRUE AFTER payroll_notifications,
  ADD COLUMN employee_notifications BOOLEAN NOT NULL DEFAULT TRUE AFTER security_notifications,
  ADD COLUMN shift_notifications BOOLEAN NOT NULL DEFAULT TRUE AFTER employee_notifications;

CREATE TABLE notification_event_preferences (
  user_id BIGINT UNSIGNED NOT NULL,
  event_type VARCHAR(50) NOT NULL,
  in_app_enabled BOOLEAN NULL,
  desktop_enabled BOOLEAN NULL,
  sound_enabled BOOLEAN NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id,event_type),
  CONSTRAINT fk_notification_event_preference_user
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE notifications
  ADD COLUMN category VARCHAR(30) NOT NULL DEFAULT 'SYSTEM' AFTER type,
  ADD COLUMN priority ENUM('NORMAL','IMPORTANT','WARNING','CRITICAL') NOT NULL DEFAULT 'NORMAL' AFTER action_url,
  ADD INDEX idx_notifications_user_category_created(user_id,category,created_at),
  ADD INDEX idx_notifications_user_type_created(user_id,type,created_at);

UPDATE notifications SET category=CASE
  WHEN type LIKE 'TASK_%' OR type='OPEN_TASK_CREATED' THEN 'TASK'
  WHEN type LIKE 'LEAVE_%' THEN 'LEAVE'
  WHEN type LIKE 'BREAK_%' THEN 'BREAK'
  WHEN type LIKE 'CALENDAR_%' OR type LIKE 'HOLIDAY_%' THEN 'CALENDAR'
  WHEN type LIKE 'PAYROLL_%' OR type LIKE 'PAYSLIP_%' OR type LIKE 'SALARY_%' THEN 'PAYROLL'
  WHEN type LIKE 'SECURITY_%' THEN 'SECURITY'
  WHEN type LIKE 'EMPLOYEE_%' THEN 'EMPLOYEE'
  WHEN type LIKE 'SHIFT_%' THEN 'SHIFT'
  WHEN type LIKE 'ANNOUNCEMENT%' OR type LIKE 'SYSTEM_%' THEN 'ANNOUNCEMENT'
  ELSE 'ATTENDANCE' END;

INSERT IGNORE INTO notification_policies(event_type,audience_type,in_app_enabled,desktop_enabled,sound_enabled) VALUES
('ATTENDANCE_CLOCK_IN','CEO_ADMIN',1,0,0),('ATTENDANCE_LATE','CEO_ADMIN',1,1,1),
('ATTENDANCE_CLOCK_OUT','CEO_ADMIN',1,0,0),('ATTENDANCE_EARLY_CLOCK_OUT','CEO_ADMIN',1,1,0),
('ATTENDANCE_MISSING_CLOCK_IN','CEO_ADMIN',1,1,1),('ATTENDANCE_MISSING_CLOCK_OUT','CEO_ADMIN',1,1,1),
('ATTENDANCE_ABSENT','CEO_ADMIN',1,1,1),('BREAK_EXCEEDED','CEO_ADMIN',1,1,1),
('LEAVE_REQUESTED','CEO_ADMIN',1,1,1),('LEAVE_CANCELLED','CEO_ADMIN',1,0,0),
('LEAVE_UPCOMING','SELECTED_EMPLOYEES',1,1,0),('LEAVE_SALARY_DEDUCTION','SELECTED_EMPLOYEES',1,1,0),
('CALENDAR_HOLIDAY_CREATED','ALL_EMPLOYEES',1,1,0),('CALENDAR_HOLIDAY_UPDATED','ALL_EMPLOYEES',1,1,0),
('CALENDAR_HOLIDAY_DELETED','ALL_EMPLOYEES',1,1,0),('CALENDAR_WEEKLY_OFF_CHANGED','ALL_EMPLOYEES',1,1,0),
('CALENDAR_UPCOMING_HOLIDAY','ALL_EMPLOYEES',1,1,0),('TASK_REASSIGNED','SELECTED_EMPLOYEES',1,1,0),
('TASK_PAUSED','SELECTED_EMPLOYEES',1,0,0),('TASK_RESUMED','SELECTED_EMPLOYEES',1,0,0),
('TASK_PRIORITY_CHANGED','SELECTED_EMPLOYEES',1,0,0),('TASK_DUE_SOON','SELECTED_EMPLOYEES',1,1,0),
('TASK_DELETED','SELECTED_EMPLOYEES',1,1,0),('SALARY_DAILY_UPDATED','SELECTED_EMPLOYEES',1,0,0),
('SALARY_DEDUCTION_ADDED','SELECTED_EMPLOYEES',1,1,0),('SALARY_BONUS_ADDED','SELECTED_EMPLOYEES',1,1,0),
('SALARY_OVERTIME_ADDED','SELECTED_EMPLOYEES',1,0,0),('PAYROLL_UPDATED','SELECTED_EMPLOYEES',1,0,0),
('PAYROLL_APPROVED','SELECTED_EMPLOYEES',1,1,0),('PAYROLL_FINALIZED','SELECTED_EMPLOYEES',1,1,0),
('PAYSLIP_AVAILABLE','SELECTED_EMPLOYEES',1,1,0),('PAYROLL_PERIOD_CLOSED','CEO_ADMIN',1,1,0),
('EMPLOYEE_UPDATED','SELECTED_EMPLOYEES',1,0,0),('EMPLOYEE_DISABLED','CEO_ADMIN',1,1,0),
('EMPLOYEE_ENABLED','SELECTED_EMPLOYEES',1,1,0),('EMPLOYEE_ROLE_CHANGED','SELECTED_EMPLOYEES',1,1,0),
('EMPLOYEE_PERMISSION_CHANGED','SELECTED_EMPLOYEES',1,1,0),('EMPLOYEE_SHIFT_CHANGED','SELECTED_EMPLOYEES',1,1,0),
('EMPLOYEE_SALARY_CHANGED','SELECTED_EMPLOYEES',1,1,0),('EMPLOYEE_MOBILE_ACCESS_CHANGED','SELECTED_EMPLOYEES',1,1,0),
('SHIFT_ASSIGNED','SELECTED_EMPLOYEES',1,1,0),('SHIFT_UPDATED','SELECTED_EMPLOYEES',1,1,0),
('SHIFT_START_REMINDER','SELECTED_EMPLOYEES',1,1,0),('SHIFT_END_REMINDER','SELECTED_EMPLOYEES',1,1,0),
('SECURITY_LOGIN','CEO_ADMIN',1,0,0),('SECURITY_NEW_DEVICE','CEO_ADMIN',1,1,1),
('SECURITY_NEW_IP','CEO_ADMIN',1,1,1),('SECURITY_FAILED_LOGIN','CEO_ADMIN',1,0,0),
('SECURITY_MULTIPLE_FAILED_LOGINS','CEO_ADMIN',1,1,1),('SECURITY_PASSWORD_CHANGED','SELECTED_EMPLOYEES',1,1,0),
('SECURITY_PERMISSION_DENIED','CEO_ADMIN',1,1,0),('SECURITY_MOBILE_ACCESS_BLOCKED','CEO_ADMIN',1,1,0),
('SECURITY_SESSION_EXPIRED','SELECTED_EMPLOYEES',1,0,0),('ANNOUNCEMENT_CREATED','ALL_EMPLOYEES',1,1,1),
('SYSTEM_MAINTENANCE','ALL_EMPLOYEES',1,1,1),('SYSTEM_UPDATE','ALL_EMPLOYEES',1,1,0),
('SYSTEM_WARNING','ALL_EMPLOYEES',1,1,1),('TEST_NOTIFICATION','SELECTED_EMPLOYEES',1,1,1);
