import { soundContent } from "./notification.service";
let configuration=null,context=null,activeAudio=null,previewing=false;
const blobs=new Map();
export const setSoundConfiguration=value=>{configuration=value;};
export const unlockAudio=async()=>{const Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx)return false;context||=new Ctx();if(context.state==="suspended")await context.resume();return context.state==="running";};
export const isAudioUnlocked=()=>Boolean(context&&context.state==="running");
export const stopPreview=()=>{if(activeAudio){activeAudio.pause();activeAudio.currentTime=0;activeAudio=null;}previewing=false;};
const builtin=(key,volume)=>{const ctx=context;if(!ctx||ctx.state!=="running")throw new Error("AUDIO_BLOCKED");const profiles={STANDARD:[[660,.12],[880,.16]],STRONG:[[520,.1],[780,.12],[1040,.18]],SOFT:[[740,.16],[920,.24]],WARNING:[[440,.16],[440,.16],[620,.22]],CRITICAL:[[380,.12],[760,.14],[380,.12],[920,.22]]};let at=ctx.currentTime;for(const[f,d]of profiles[key]||profiles.STANDARD){const o=ctx.createOscillator(),g=ctx.createGain();o.type=key==="SOFT"?"sine":"triangle";o.frequency.value=f;g.gain.setValueAtTime(.0001,at);g.gain.exponentialRampToValueAtTime(Math.max(.0001,.28*volume),at+.015);g.gain.exponentialRampToValueAtTime(.0001,at+d);o.connect(g).connect(ctx.destination);o.start(at);o.stop(at+d+.01);at+=d*.82;}};
const choose=(notification={},soundId)=>{const sounds=configuration?.sounds||[],assignments=configuration?.assignments||[];const assigned=soundId||assignments.find(x=>x.scopeType==="EVENT"&&x.scopeKey===notification.type)?.soundId||assignments.find(x=>x.scopeType==="CATEGORY"&&x.scopeKey===(notification.category||"SYSTEM"))?.soundId||configuration?.settings?.defaultSoundId;return sounds.find(x=>Number(x.id)===Number(assigned))||sounds.find(x=>x.builtinKey==="STANDARD");};
const volumeFor=(notification,personal=100)=>{const priority=notification.priority||"NORMAL",settings=configuration?.settings||{},key={NORMAL:"normalVolume",IMPORTANT:"importantVolume",WARNING:"warningVolume",CRITICAL:"criticalVolume"}[priority],normal=Math.max(1,Number(settings.normalVolume??70)),profile=Number(settings[key]??normal),master=Number(personal);return Math.min(1,Math.max(0,(master/100)*(profile/normal)));};
export async function playSound({notification={},soundId=null,volume=100,preview=false}={}){if(preview)stopPreview();if(!await unlockAudio())throw new Error("AUDIO_BLOCKED");const sound=choose(notification,soundId),level=volumeFor(notification,volume);if(!sound||level<=0)return;if(sound.isBuiltin){builtin(sound.builtinKey,level);return;}let url=blobs.get(sound.id);if(!url){url=URL.createObjectURL(await soundContent(sound.id));blobs.set(sound.id,url);}const audio=new Audio(url);audio.volume=level;activeAudio=audio;previewing=preview;audio.onended=()=>{if(activeAudio===audio)activeAudio=null;previewing=false;};audio.onerror=()=>{if(activeAudio===audio)activeAudio=null;previewing=false;};await audio.play();}
export const previewSound=(soundId,volume=100)=>playSound({soundId,volume,preview:true});
export const playNotificationSound=(notification,volume)=>previewing?Promise.resolve():playSound({notification,volume});
