import pool from "../config/database.js";
import ApiError from "../utils/ApiError.js";
const select="SELECT ow.id,ow.employee_id employeeId,ow.title,ow.description,ow.status,ow.started_at startedAt,ow.completed_at completedAt,ow.created_at createdAt,ow.updated_at updatedAt,CONCAT(e.first_name,' ',e.last_name) employeeName FROM ongoing_work ow JOIN employees e ON e.id=ow.employee_id";
async function management(user){const[[r]]=await pool.execute("SELECT EXISTS(SELECT 1 FROM user_roles ur JOIN roles r ON r.id=ur.role_id WHERE ur.user_id=? AND UPPER(r.name) IN('CEO','ADMIN','SUPER_ADMIN')) yes",[user.id]);return Boolean(r.yes)}
function employee(user){if(!user.employee_id)throw new ApiError(403,"This account is not linked to an employee");return Number(user.employee_id)}
export async function mine(user){if(await management(user))throw new ApiError(403,"Management can view ongoing work through Team Availability");const id=employee(user),[rows]=await pool.execute(`${select} WHERE ow.employee_id=? ORDER BY FIELD(ow.status,'ONGOING','PAUSED','COMPLETED'),ow.updated_at DESC LIMIT 50`,[id]);return rows}
export async function team(user){if(!await management(user))throw new ApiError(403,"Only management can view all ongoing work");const[rows]=await pool.execute(`${select} WHERE ow.status IN('ONGOING','PAUSED') ORDER BY e.first_name,e.last_name`);return rows}
export async function create(data,user){if(await management(user))throw new ApiError(403,"Only employees can create personal ongoing work");const id=employee(user),c=await pool.getConnection();try{await c.beginTransaction();await c.execute("SELECT id FROM employees WHERE id=? FOR UPDATE",[id]);const[[existing]]=await c.execute("SELECT id FROM ongoing_work WHERE employee_id=? AND status IN('ONGOING','PAUSED') LIMIT 1",[id]);if(existing)throw new ApiError(409,"Complete or delete your current ongoing work before adding another");const[r]=await c.execute("INSERT INTO ongoing_work(employee_id,title,description,status,started_at)VALUES(?,?,?,'ONGOING',CURRENT_TIMESTAMP)",[id,data.title,data.description||null]);await c.commit();return getOwn(r.insertId,user)}catch(e){await c.rollback();throw e}finally{c.release()}}
async function getOwn(id,user){if(await management(user))throw new ApiError(403,"Management cannot modify employee ongoing work");const[[row]]=await pool.execute(`${select} WHERE ow.id=? AND ow.employee_id=?`,[id,employee(user)]);if(!row)throw new ApiError(404,"Ongoing work item not found");return row}
export async function update(id,data,user){await getOwn(id,user);await pool.execute("UPDATE ongoing_work SET title=?,description=? WHERE id=?",[data.title,data.description||null,id]);return getOwn(id,user)}
export async function setStatus(id,data,user){const row=await getOwn(id,user);if(row.status==='COMPLETED')throw new ApiError(409,"Completed ongoing work cannot be resumed");await pool.execute("UPDATE ongoing_work SET status=?,started_at=IF(?='ONGOING' AND started_at IS NULL,CURRENT_TIMESTAMP,started_at),completed_at=IF(?='COMPLETED',CURRENT_TIMESTAMP,NULL) WHERE id=?",[data.status,data.status,data.status,id]);return getOwn(id,user)}
export async function remove(id,user){await getOwn(id,user);await pool.execute("DELETE FROM ongoing_work WHERE id=?",[id]);return{deleted:true,id:Number(id)}}
