import pool from "../config/database.js";
import ApiError from "../utils/ApiError.js";
import { insertReminder } from "./scheduledWorkReminder.service.js";
import { displayStatus, parseExact, relativeDate, sqlToIso, toSqlDateTime } from "../utils/scheduledWorkTime.js";
import { completeOngoingWork } from "./ongoingWork.service.js";

export const RECURRENCE_FUTURE_WINDOW = 8;
const occurrenceSelect = `SELECT o.id occurrenceId,o.scheduled_work_id id,o.assigned_to assignedTo,o.occurrence_number occurrenceNumber,
 o.scheduled_at scheduledAt,o.status,o.started_at startedAt,o.completed_at completedAt,o.cancelled_at cancelledAt,
 o.created_at createdAt,w.title,w.description,w.priority,w.recurrence_type recurrenceType,w.recurrence_interval recurrenceInterval,
 w.recurrence_unit recurrenceUnit,w.recurrence_config recurrenceConfig,w.recurrence_status recurrenceStatus
 ,(SELECT GROUP_CONCAT(CONCAT(r.reminder_type,':',COALESCE(r.reminder_value,''),':',COALESCE(r.reminder_unit,''),':',r.status) ORDER BY r.remind_at SEPARATOR '|') FROM scheduled_work_reminders r WHERE r.occurrence_id=o.id AND r.status='PENDING') reminderSummary
 ,(SELECT s.id FROM scheduled_work_snoozes s WHERE s.occurrence_id=o.id AND s.status='PENDING' ORDER BY s.snoozed_until DESC LIMIT 1) activeSnoozeId
 ,(SELECT s.snoozed_until FROM scheduled_work_snoozes s WHERE s.occurrence_id=o.id AND s.status='PENDING' ORDER BY s.snoozed_until DESC LIMIT 1) activeSnoozedUntil
 ,w.linked_task_id linkedTaskId,(SELECT t.title FROM tasks t WHERE t.id=w.linked_task_id) linkedTaskTitle,(SELECT t.status FROM tasks t WHERE t.id=w.linked_task_id) linkedTaskStatus
 ,(SELECT ow.id FROM ongoing_work ow WHERE ow.source_occurrence_id=o.id AND ow.deleted_at IS NULL LIMIT 1) ongoingWorkId
 ,(SELECT ow.status FROM ongoing_work ow WHERE ow.source_occurrence_id=o.id AND ow.deleted_at IS NULL LIMIT 1) ongoingWorkStatus
 FROM scheduled_work_occurrences o JOIN scheduled_work w ON w.id=o.scheduled_work_id`;
const asConfig = (value) => typeof value === "string" ? JSON.parse(value || "{}") : value || {};
const localParts = (date) => Object.fromEntries(new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Karachi",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23",weekday:"short"}).formatToParts(date).filter(x=>x.type!=="literal").map(x=>[x.type,x.value]));
const localDate = (year,month,day,time) => new Date(`${year}-${String(month).padStart(2,"0")}-${String(day).padStart(2,"0")}T${time}+05:00`);
const daysInMonth = (year,month) => new Date(Date.UTC(year,month,0)).getUTCDate();
const weekdayFormatter = new Intl.DateTimeFormat("en-US", { timeZone: "Asia/Karachi", weekday: "short" });
const weekday = (date) => ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].indexOf(weekdayFormatter.format(date));

export function nextOccurrence(previous, rule) {
  const prev = previous instanceof Date
    ? previous
    : new Date(String(previous).includes("T") ? previous : sqlToIso(previous));
  const config=asConfig(rule.recurrenceConfig), p=localParts(prev), interval=Number(rule.recurrenceInterval||1), time=`${p.hour}:${p.minute}:${p.second}`;
  if(rule.recurrenceType==="CUSTOM_INTERVAL"&&rule.recurrenceUnit==="HOURS") return new Date(prev.getTime()+interval*3600000);
  if(rule.recurrenceType==="WEEKLY"){
    const selected=(config.weekdays||[weekday(prev)]).map(Number).sort((a,b)=>a-b);
    const current=weekday(prev);
    const later=selected.find(day=>day>current);
    const delta=later!==undefined?later-current:(7-current+selected[0])+(interval-1)*7;
    const candidate=new Date(prev.getTime()+delta*86400000),c=localParts(candidate);
    return localDate(c.year,c.month,c.day,time);
  }
  const months = rule.recurrenceType==="MONTHLY" ? interval : rule.recurrenceType==="CUSTOM_INTERVAL"&&rule.recurrenceUnit==="MONTHS" ? interval : 0;
  if(months){let year=Number(p.year),month=Number(p.month)+months;year+=Math.floor((month-1)/12);month=((month-1)%12)+1;const requested=Number(config.monthDay||p.day);return localDate(year,month,Math.min(requested,daysInMonth(year,month)),time);}
  const days=rule.recurrenceType==="DAILY"?interval:interval*(rule.recurrenceUnit==="WEEKS"?7:1);const candidate=new Date(prev.getTime()+days*86400000),c=localParts(candidate);return localDate(c.year,c.month,c.day,time);
}
export function occurrencePresentation(row,now=new Date()){const result={...row,isOccurrence:true,isRecurring:true,displayStatus:displayStatus(row,now),recurrenceConfig:asConfig(row.recurrenceConfig)};result.reminders=result.reminderSummary?result.reminderSummary.split("|").map(item=>{const [reminderType,value,unit,status]=item.split(":");return{reminderType,value:value?Number(value):null,unit:unit||null,status};}):[];delete result.reminderSummary;result.activeSnooze=result.activeSnoozeId?{id:Number(result.activeSnoozeId),snoozedUntil:sqlToIso(result.activeSnoozedUntil)}:null;delete result.activeSnoozeId;delete result.activeSnoozedUntil;if(result.ongoingWorkId&&result.ongoingWorkStatus!=="COMPLETED"&&result.status==="UPCOMING")result.displayStatus="IN_PROGRESS";for(const key of ["scheduledAt","startedAt","completedAt","cancelledAt","createdAt"])result[key]=sqlToIso(result[key]);return result;}
const withinEnd=(date,number,rule)=>rule.recurrenceEndType==="ON_DATE"?date<=new Date(sqlToIso(rule.recurrenceEndAt)):rule.recurrenceEndType==="AFTER_OCCURRENCES"?number<=Number(rule.recurrenceMaxOccurrences):true;
export async function generateForParent(connection,parent,{skipPast=false}={}){
  if(!parent.isRecurring||parent.recurrenceStatus!=="ACTIVE")return 0;
  const [[last]]=await connection.execute("SELECT occurrence_number occurrenceNumber,scheduled_at scheduledAt FROM scheduled_work_occurrences WHERE scheduled_work_id=? AND status<>'CANCELLED' ORDER BY scheduled_at DESC LIMIT 1 FOR UPDATE",[parent.id]);
  const [[sequence]]=await connection.execute("SELECT COALESCE(MAX(occurrence_number),0) lastNumber FROM scheduled_work_occurrences WHERE scheduled_work_id=?",[parent.id]);
  const [[windowState]]=await connection.execute("SELECT COUNT(*) futureCount FROM scheduled_work_occurrences WHERE scheduled_work_id=? AND status='UPCOMING' AND scheduled_at>CURRENT_TIMESTAMP",[parent.id]);
  let number=Number(sequence.lastNumber)+1,date=last?nextOccurrence(last.scheduledAt,parent):new Date(sqlToIso(parent.recurrenceStartAt));let created=0,future=Number(windowState.futureCount),guard=0;
  while(future<RECURRENCE_FUTURE_WINDOW&&guard++<500&&withinEnd(date,number,parent)){
    if(skipPast&&date<=new Date()){date=nextOccurrence(date,parent);continue;}
    const scheduledAt=toSqlDateTime(date);let occurrenceId=null,active=false;
    const [[existing]]=await connection.execute("SELECT id,status FROM scheduled_work_occurrences WHERE scheduled_work_id=? AND scheduled_at=? FOR UPDATE",[parent.id,scheduledAt]);
    if(existing?.status==="CANCELLED"){await connection.execute("UPDATE scheduled_work_occurrences SET status='UPCOMING',cancelled_at=NULL WHERE id=?",[existing.id]);occurrenceId=existing.id;active=true;}
    else if(existing?.status==="UPCOMING")active=true;
    else if(!existing){const [insert]=await connection.execute("INSERT IGNORE INTO scheduled_work_occurrences(scheduled_work_id,assigned_to,occurrence_number,scheduled_at) VALUES(?,?,?,?)",[parent.id,parent.assignedTo,number,scheduledAt]);if(insert.insertId){occurrenceId=insert.insertId;active=true;}}
    if(occurrenceId){const reminders=asConfig(parent.recurrenceReminders);for(const reminder of Array.isArray(reminders)?reminders:[])try{await insertReminder(connection,parent.id,scheduledAt,reminder,new Date(),occurrenceId);}catch(error){if(error.code!=="REMINDER_IN_PAST")throw error;}try{await insertReminder(connection,parent.id,scheduledAt,{atTime:true},new Date(),occurrenceId);}catch(error){if(error.code!=="REMINDER_IN_PAST")throw error;}created++;}
    if(active&&date>new Date())future++;date=nextOccurrence(date,parent);number++;
  }return created;
}
const parentSelect=`SELECT id,assigned_to assignedTo,is_recurring isRecurring,recurrence_type recurrenceType,recurrence_interval recurrenceInterval,recurrence_unit recurrenceUnit,recurrence_config recurrenceConfig,recurrence_reminders recurrenceReminders,recurrence_start_at recurrenceStartAt,recurrence_end_type recurrenceEndType,recurrence_end_at recurrenceEndAt,recurrence_max_occurrences recurrenceMaxOccurrences,recurrence_status recurrenceStatus FROM scheduled_work`;
export async function generateActiveRecurrences({batchSize=50}={}){const [ids]=await pool.execute("SELECT id FROM scheduled_work WHERE is_recurring=TRUE AND recurrence_status='ACTIVE' ORDER BY id LIMIT ?",[batchSize]);let generated=0;for(const {id} of ids){const connection=await pool.getConnection();try{await connection.beginTransaction();const [[parent]]=await connection.execute(`${parentSelect} WHERE id=? FOR UPDATE`,[id]);generated+=await generateForParent(connection,parent);await connection.commit();}catch(error){await connection.rollback();console.error("Recurring occurrence generation failed",{scheduledWorkId:id,message:error.message});}finally{connection.release();}}return{parents:ids.length,generated};}
async function ownedParent(id,actor,connection=pool,lock=false){const [[row]]=await connection.execute(`${parentSelect} WHERE id=? AND assigned_to=? AND is_recurring=TRUE${lock?" FOR UPDATE":""}`,[id,actor.employee_id]);if(!row)throw new ApiError(404,"Recurring scheduled work was not found.");return row;}
export async function listRecurring(actor){const [rows]=await pool.execute(`SELECT w.id,w.title,w.description,w.priority,w.recurrence_type recurrenceType,w.recurrence_interval recurrenceInterval,w.recurrence_unit recurrenceUnit,w.recurrence_config recurrenceConfig,w.recurrence_status recurrenceStatus,w.recurrence_end_type recurrenceEndType,w.recurrence_end_at recurrenceEndAt,w.recurrence_max_occurrences recurrenceMaxOccurrences,(SELECT MIN(o.scheduled_at) FROM scheduled_work_occurrences o WHERE o.scheduled_work_id=w.id AND o.status='UPCOMING' AND o.scheduled_at>CURRENT_TIMESTAMP) nextOccurrenceAt FROM scheduled_work w WHERE w.assigned_to=? AND w.is_recurring=TRUE ORDER BY nextOccurrenceAt`,[actor.employee_id]);return rows.map(r=>({...r,isRecurring:true,recurrenceConfig:asConfig(r.recurrenceConfig),recurrenceEndAt:sqlToIso(r.recurrenceEndAt),nextOccurrenceAt:sqlToIso(r.nextOccurrenceAt)}));}
export async function listOccurrences(id,filters,actor){await ownedParent(id,actor);const where=["o.scheduled_work_id=?"],params=[id];if(filters.status)where.push("o.status=?"),params.push(filters.status);if(filters.from)where.push("o.scheduled_at>=?"),params.push(`${filters.from} 00:00:00`);if(filters.to)where.push("o.scheduled_at<DATE_ADD(?,INTERVAL 1 DAY)"),params.push(`${filters.to} 00:00:00`);const page=filters.page||1,limit=filters.limit||20;const [rows]=await pool.execute(`${occurrenceSelect} WHERE ${where.join(" AND ")} ORDER BY o.scheduled_at DESC LIMIT ? OFFSET ?`,[...params,limit,(page-1)*limit]);const [[count]]=await pool.execute(`SELECT COUNT(*) total FROM scheduled_work_occurrences o WHERE ${where.join(" AND ")}`,params);return{items:rows.map(r=>occurrencePresentation(r)),pagination:{page,limit,total:Number(count.total),pages:Math.ceil(Number(count.total)/limit)}};}
export async function getOccurrence(id,occurrenceId,actor){await ownedParent(id,actor);const [[row]]=await pool.execute(`${occurrenceSelect} WHERE o.scheduled_work_id=? AND o.id=? AND o.assigned_to=?`,[id,occurrenceId,actor.employee_id]);if(!row)throw new ApiError(404,"Scheduled work occurrence was not found.");return occurrencePresentation(row);}
async function recurrenceAction(id,actor,next){const connection=await pool.getConnection();try{await connection.beginTransaction();const parent=await ownedParent(id,actor,connection,true);if(parent.recurrenceStatus===next){await connection.commit();return{status:next};}await connection.execute("UPDATE scheduled_work SET recurrence_status=? WHERE id=?",[next,id]);if(next!=="ACTIVE"){const [future]=await connection.execute("SELECT id FROM scheduled_work_occurrences WHERE scheduled_work_id=? AND status='UPCOMING' AND started_at IS NULL AND scheduled_at>CURRENT_TIMESTAMP FOR UPDATE",[id]);const ids=future.map(x=>x.id);if(ids.length){const marks=ids.map(()=>"?").join(",");await connection.execute(`UPDATE scheduled_work_occurrences SET status='CANCELLED',cancelled_at=CURRENT_TIMESTAMP WHERE id IN(${marks})`,ids);await connection.execute(`UPDATE scheduled_work_reminders SET status='CANCELLED' WHERE occurrence_id IN(${marks}) AND status='PENDING'`,ids);await connection.execute(`UPDATE scheduled_work_snoozes SET status='CANCELLED' WHERE occurrence_id IN(${marks}) AND status='PENDING'`,ids);}}else await generateForParent(connection,{...parent,recurrenceStatus:"ACTIVE"},{skipPast:true});const event=next==="ACTIVE"?"RESUMED":next;await connection.execute("INSERT INTO audit_logs(user_id,employee_id,action,entity_type,entity_id,description) VALUES(?,?,?,'SCHEDULED_WORK',?,?)",[actor.id,actor.employee_id,`SCHEDULED_WORK_RECURRENCE_${event}`,id,`Recurring scheduled work ${next.toLowerCase()}.`]);await connection.commit();return{status:next};}catch(e){await connection.rollback();throw e;}finally{connection.release();}}
export const pauseRecurrence=(id,actor)=>recurrenceAction(id,actor,"PAUSED");export const resumeRecurrence=(id,actor)=>recurrenceAction(id,actor,"ACTIVE");export const endRecurrence=(id,actor)=>recurrenceAction(id,actor,"ENDED");
export async function updateRecurrence(id,repeat,actor){const connection=await pool.getConnection();try{await connection.beginTransaction();const parent=await ownedParent(id,actor,connection,true);if(parent.recurrenceStatus==="ENDED")throw new ApiError(409,"An ended recurrence cannot be edited.");const [future]=await connection.execute("SELECT id FROM scheduled_work_occurrences WHERE scheduled_work_id=? AND status='UPCOMING' AND started_at IS NULL AND scheduled_at>CURRENT_TIMESTAMP FOR UPDATE",[id]);const ids=future.map(x=>x.id);if(ids.length){const marks=ids.map(()=>"?").join(",");await connection.execute(`UPDATE scheduled_work_occurrences SET status='CANCELLED',cancelled_at=CURRENT_TIMESTAMP WHERE id IN(${marks})`,ids);await connection.execute(`UPDATE scheduled_work_reminders SET status='CANCELLED' WHERE occurrence_id IN(${marks}) AND status='PENDING'`,ids);await connection.execute(`UPDATE scheduled_work_snoozes SET status='CANCELLED' WHERE occurrence_id IN(${marks}) AND status='PENDING'`,ids);}const config=JSON.stringify({weekdays:repeat.weekdays||[],monthDay:repeat.monthDay||null}),endAt=repeat.endType==="ON_DATE"?`${repeat.endAt} 23:59:59`:null,unit=repeat.type==="DAILY"?"DAYS":repeat.type==="WEEKLY"?"WEEKS":repeat.type==="MONTHLY"?"MONTHS":repeat.unit;await connection.execute("UPDATE scheduled_work SET recurrence_type=?,recurrence_interval=?,recurrence_unit=?,recurrence_config=?,recurrence_end_type=?,recurrence_end_at=?,recurrence_max_occurrences=? WHERE id=?",[repeat.type,repeat.interval,unit,config,repeat.endType,endAt,repeat.maxOccurrences||null,id]);const updated={...parent,recurrenceType:repeat.type,recurrenceInterval:repeat.interval,recurrenceUnit:unit,recurrenceConfig:config,recurrenceEndType:repeat.endType,recurrenceEndAt:endAt,recurrenceMaxOccurrences:repeat.maxOccurrences||null};if(parent.recurrenceStatus==="ACTIVE")await generateForParent(connection,updated,{skipPast:true});await connection.execute("INSERT INTO audit_logs(user_id,employee_id,action,entity_type,entity_id,description,new_values) VALUES(?,?,?,'SCHEDULED_WORK',?,?,?)",[actor.id,actor.employee_id,"SCHEDULED_WORK_RECURRENCE_UPDATED",id,"Recurring scheduled work updated.",JSON.stringify({scheduledWorkId:Number(id),oldRule:{type:parent.recurrenceType,interval:parent.recurrenceInterval,unit:parent.recurrenceUnit},newRule:{type:repeat.type,interval:repeat.interval,unit}})]);await connection.commit();return{status:parent.recurrenceStatus};}catch(error){await connection.rollback();throw error;}finally{connection.release();}}
async function occurrenceAction(workId,occurrenceId,actor,action,options={}){const connection=await pool.getConnection();try{await connection.beginTransaction();await ownedParent(workId,actor,connection,true);const [[row]]=await connection.execute(`${occurrenceSelect} WHERE o.id=? AND o.scheduled_work_id=? AND o.assigned_to=? FOR UPDATE`,[occurrenceId,workId,actor.employee_id]);if(!row)throw new ApiError(404,"Scheduled work occurrence was not found.");if(row.status!=="UPCOMING")throw new ApiError(409,`This occurrence is already ${row.status.toLowerCase()}.`);if(action==="START"){if(!row.startedAt){await connection.execute("UPDATE scheduled_work_occurrences SET started_at=CURRENT_TIMESTAMP WHERE id=?",[occurrenceId]);await connection.execute("INSERT INTO audit_logs(user_id,employee_id,action,entity_type,entity_id,description,new_values) VALUES(?,?,?,'SCHEDULED_WORK_OCCURRENCE',?,?,?)",[actor.id,actor.employee_id,"SCHEDULED_WORK_OCCURRENCE_STARTED",occurrenceId,"Recurring occurrence started.",JSON.stringify({scheduledWorkId:Number(workId),occurrenceId:Number(occurrenceId),scheduledAt:row.scheduledAt})]);}}else{const [[execution]]=await connection.execute("SELECT id,status FROM ongoing_work WHERE source_occurrence_id=? AND deleted_at IS NULL LIMIT 1 FOR UPDATE",[occurrenceId]);if(execution&&execution.status!=="COMPLETED"&&!options.executionHandling)throw new ApiError(409,"Active ongoing work is linked to this occurrence. Choose whether to complete both or the schedule only.","ACTIVE_ONGOING_WORK");if(execution&&execution.status!=="COMPLETED"&&options.executionHandling==="COMPLETE_BOTH")await completeOngoingWork(connection,execution.id,{completionNote:"Completed from Scheduled Work.",completeLinkedSchedule:false},actor);await connection.execute("UPDATE scheduled_work_occurrences SET status='COMPLETED',completed_at=CURRENT_TIMESTAMP WHERE id=?",[occurrenceId]);await connection.execute("UPDATE scheduled_work_reminders SET status='CANCELLED' WHERE occurrence_id=? AND status='PENDING'",[occurrenceId]);await connection.execute("UPDATE scheduled_work_snoozes SET status='CANCELLED' WHERE occurrence_id=? AND status='PENDING'",[occurrenceId]);await connection.execute("INSERT INTO audit_logs(user_id,employee_id,action,entity_type,entity_id,description,new_values) VALUES(?,?,?,'SCHEDULED_WORK_OCCURRENCE',?,?,?)",[actor.id,actor.employee_id,"SCHEDULED_WORK_OCCURRENCE_COMPLETED",occurrenceId,"Recurring occurrence completed.",JSON.stringify({scheduledWorkId:Number(workId),occurrenceId:Number(occurrenceId),scheduledAt:row.scheduledAt})]);}await connection.commit();const [[updated]]=await pool.execute(`${occurrenceSelect} WHERE o.id=?`,[occurrenceId]);return occurrencePresentation(updated);}catch(e){await connection.rollback();throw e;}finally{connection.release();}}
export const startOccurrence=(workId,occurrenceId,actor)=>occurrenceAction(workId,occurrenceId,actor,"START");export const completeOccurrence=(workId,occurrenceId,actor,options)=>occurrenceAction(workId,occurrenceId,actor,"COMPLETE",options);
export async function rescheduleOccurrence(workId,occurrenceId,data,actor){const connection=await pool.getConnection();try{await connection.beginTransaction();const parent=await ownedParent(workId,actor,connection,true);const [[row]]=await connection.execute("SELECT id,status,scheduled_at scheduledAt,started_at startedAt FROM scheduled_work_occurrences WHERE id=? AND scheduled_work_id=? AND assigned_to=? FOR UPDATE",[occurrenceId,workId,actor.employee_id]);if(!row)throw new ApiError(404,"Scheduled work occurrence was not found.");if(row.status!=="UPCOMING")throw new ApiError(409,"Only an upcoming occurrence can be rescheduled.");const [[execution]]=await connection.execute("SELECT id,status FROM ongoing_work WHERE source_occurrence_id=? AND deleted_at IS NULL LIMIT 1 FOR UPDATE",[occurrenceId]);if(execution&&execution.status!=="COMPLETED"&&!data.confirmActiveExecution)throw new ApiError(409,"This occurrence has already started. Confirm that rescheduling will not change its Ongoing Work.","ACTIVE_ONGOING_WORK");const date=data.scheduleType==="RELATIVE"?relativeDate(data.relativeValue,data.relativeUnit):parseExact(data.scheduledAt);if(!date||date<=new Date())throw new ApiError(400,"The selected time must be in the future.","SCHEDULE_MUST_BE_FUTURE");const scheduledAt=toSqlDateTime(date);await connection.execute("UPDATE scheduled_work_occurrences SET scheduled_at=? WHERE id=?",[scheduledAt,occurrenceId]);await connection.execute("UPDATE scheduled_work_reminders SET status='CANCELLED' WHERE occurrence_id=? AND status='PENDING'",[occurrenceId]);await connection.execute("UPDATE scheduled_work_snoozes SET status='CANCELLED' WHERE occurrence_id=? AND status='PENDING'",[occurrenceId]);const reminders=asConfig(parent.recurrenceReminders);for(const reminder of Array.isArray(reminders)?reminders:[])try{await insertReminder(connection,workId,scheduledAt,reminder,new Date(),occurrenceId);}catch(error){if(error.code!=="REMINDER_IN_PAST")throw error;}await insertReminder(connection,workId,scheduledAt,{atTime:true},new Date(),occurrenceId);await connection.execute("INSERT INTO audit_logs(user_id,employee_id,action,entity_type,entity_id,description,new_values) VALUES(?,?,?,'SCHEDULED_WORK_OCCURRENCE',?,?,?)",[actor.id,actor.employee_id,"SCHEDULED_WORK_OCCURRENCE_RESCHEDULED",occurrenceId,"Recurring occurrence rescheduled.",JSON.stringify({scheduledWorkId:Number(workId),occurrenceId:Number(occurrenceId),oldScheduledAt:row.scheduledAt,newScheduledAt:scheduledAt})]);await connection.commit();const [[updated]]=await pool.execute(`${occurrenceSelect} WHERE o.id=?`,[occurrenceId]);return occurrencePresentation(updated);}catch(error){await connection.rollback();if(error.code==="ER_DUP_ENTRY")throw new ApiError(409,"Another occurrence already exists at that time.");throw error;}finally{connection.release();}}
export async function occurrenceRowsForList(actor,filters,mode,limit=100){const where=["o.assigned_to=?"],params=[actor.employee_id];if(mode==="today"||filters.status==="DUE_TODAY")where.push("o.status='UPCOMING'","o.scheduled_at>=CURRENT_DATE","o.scheduled_at<DATE_ADD(CURRENT_DATE,INTERVAL 1 DAY)");else if(mode==="upcoming"||filters.status==="UPCOMING")where.push("o.status='UPCOMING'","o.scheduled_at>CURRENT_TIMESTAMP");else if(mode==="overdue"||filters.status==="OVERDUE")where.push("o.status='UPCOMING'","o.scheduled_at<CURRENT_TIMESTAMP");else if(filters.status)where.push("o.status=?"),params.push(filters.status);if(filters.priority)where.push("w.priority=?"),params.push(filters.priority);if(filters.search)where.push("(w.title LIKE ? OR w.description LIKE ?)"),params.push(`%${filters.search}%`,`%${filters.search}%`);if(filters.from)where.push("o.scheduled_at>=?"),params.push(`${filters.from} 00:00:00`);if(filters.to)where.push("o.scheduled_at<DATE_ADD(?,INTERVAL 1 DAY)"),params.push(`${filters.to} 00:00:00`);const order=filters.status==="COMPLETED"?"o.completed_at DESC":"o.scheduled_at ASC";const [rows]=await pool.execute(`${occurrenceSelect} WHERE ${where.join(" AND ")} ORDER BY ${order} LIMIT ?`,[...params,limit]);const [[count]]=await pool.execute(`SELECT COUNT(*) total FROM scheduled_work_occurrences o JOIN scheduled_work w ON w.id=o.scheduled_work_id WHERE ${where.join(" AND ")}`,params);return{items:rows.map(r=>occurrencePresentation(r)),total:Number(count.total)};}
